[build]
builder = "dockerfile"

[deploy]
# Temporarily disable healthcheck to verify app works
# port = 80
# healthcheckPath = "/control/"
# healthcheckTimeout = 90
# healthcheckInterval = 30
# healthcheckRetries = 10
